apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rex-nginx
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: rex-nginx
    spec:
      containers:
        - name: rex-nginx
          image: nginx
